// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAdminAccess = "admin_access"

// AdminAccess mapped from table <admin_access>
type AdminAccess struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	AdminID   string    `gorm:"column:admin_id" json:"admin_id"`
	AccessID  string    `gorm:"column:access_id" json:"access_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted   bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName AdminAccess's table name
func (*AdminAccess) TableName() string {
	return TableNameAdminAccess
}
