// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAttachment = "attachment"

// Attachment mapped from table <attachment>
type Attachment struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	PostID         string    `gorm:"column:post_id" json:"post_id"`
	AttachmentType string    `gorm:"column:attachment_type" json:"attachment_type"`
	MimeType       string    `gorm:"column:mime_type;not null" json:"mime_type"`
	Ext            string    `gorm:"column:ext;not null" json:"ext"`
	Value          string    `gorm:"column:value" json:"value"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted        bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName Attachment's table name
func (*Attachment) TableName() string {
	return TableNameAttachment
}
