// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGroupMember = "group_member"

// GroupMember mapped from table <group_member>
type GroupMember struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	GroupID   string    `gorm:"column:group_id" json:"group_id"`
	UserID    string    `gorm:"column:user_id" json:"user_id"`
	Role      string    `gorm:"column:role" json:"role"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted   bool      `gorm:"column:deleted" json:"deleted"`
}

// TableName GroupMember's table name
func (*GroupMember) TableName() string {
	return TableNameGroupMember
}
