// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePostComment = "post_comment"

// PostComment mapped from table <post_comment>
type PostComment struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Body      string    `gorm:"column:body" json:"body"`
	UserID    string    `gorm:"column:user_id" json:"user_id"`
	ReplyTo   string    `gorm:"column:reply_to" json:"reply_to"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted   bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName PostComment's table name
func (*PostComment) TableName() string {
	return TableNamePostComment
}
