// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePostHashtag = "post_hashtag"

// PostHashtag mapped from table <post_hashtag>
type PostHashtag struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	PostID    string    `gorm:"column:post_id" json:"post_id"`
	HashtagID string    `gorm:"column:hashtag_id" json:"hashtag_id"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	Deleted   bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName PostHashtag's table name
func (*PostHashtag) TableName() string {
	return TableNamePostHashtag
}
