// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Context     string    `gorm:"column:context;not null" json:"context"`
	Note        string    `gorm:"column:note;not null" json:"note"`
	ReferenceID string    `gorm:"column:reference_id" json:"reference_id"`
	ReportedBy  string    `gorm:"column:reported_by" json:"reported_by"`
	Status      string    `gorm:"column:status" json:"status"`
	ReportType  string    `gorm:"column:report_type" json:"report_type"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted     bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
