// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSeaqlMigration = "seaql_migrations"

// SeaqlMigration mapped from table <seaql_migrations>
type SeaqlMigration struct {
	Version   string `gorm:"column:version;primaryKey" json:"version"`
	AppliedAt int64  `gorm:"column:applied_at;not null" json:"applied_at"`
}

// TableName SeaqlMigration's table name
func (*SeaqlMigration) TableName() string {
	return TableNameSeaqlMigration
}
