// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameThread = "threads"

// Thread mapped from table <threads>
type Thread struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	ThreadID    string    `gorm:"column:thread_id" json:"thread_id"`
	GroupID     string    `gorm:"column:group_id" json:"group_id"`
	Title       string    `gorm:"column:title" json:"title"`
	Description string    `gorm:"column:description" json:"description"`
	Upvote      int64     `gorm:"column:upvote;not null" json:"upvote"`
	DownVote    int64     `gorm:"column:down_vote;not null" json:"down_vote"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted     bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName Thread's table name
func (*Thread) TableName() string {
	return TableNameThread
}
