// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameThreadsComment = "threads_comment"

// ThreadsComment mapped from table <threads_comment>
type ThreadsComment struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ThreadID  string    `gorm:"column:thread_id" json:"thread_id"`
	ReplyTo   string    `gorm:"column:reply_to" json:"reply_to"`
	Body      string    `gorm:"column:body" json:"body"`
	Upvote    int64     `gorm:"column:upvote;not null" json:"upvote"`
	DownVote  int64     `gorm:"column:down_vote;not null" json:"down_vote"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted   bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName ThreadsComment's table name
func (*ThreadsComment) TableName() string {
	return TableNameThreadsComment
}
