// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserCredential = "user_credential"

// UserCredential mapped from table <user_credential>
type UserCredential struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	Password     string    `gorm:"column:password;not null" json:"password"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	FullName     string    `gorm:"column:full_name;not null" json:"full_name"`
	DateOfBirth  time.Time `gorm:"column:date_of_birth" json:"date_of_birth"`
	Gender       string    `gorm:"column:gender" json:"gender"`
	Status       string    `gorm:"column:status;not null" json:"status"`
	AuthProvider string    `gorm:"column:auth_provider;not null" json:"auth_provider"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted      bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName UserCredential's table name
func (*UserCredential) TableName() string {
	return TableNameUserCredential
}
