// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserNotification = "user_notification"

// UserNotification mapped from table <user_notification>
type UserNotification struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	UserID         string    `gorm:"column:user_id" json:"user_id"`
	NotificationID string    `gorm:"column:notification_id" json:"notification_id"`
	Body           string    `gorm:"column:body" json:"body"`
	IsRead         string    `gorm:"column:is_read" json:"is_read"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted        bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName UserNotification's table name
func (*UserNotification) TableName() string {
	return TableNameUserNotification
}
